packages: 
  device: !include device/device.yaml
  sensors: !include sensors/office-ceiling-fan.yaml
  time: !include time/time.yaml
  backlight: !include addon/backlight.yaml
  images: !include assets/images.yaml
  fonts: !include assets/fonts.yaml
  icons: !include assets/icons.yaml
  button: !include theme/button.yaml
  ui: !include ui/lvgl.yaml
